[PATCH 2/2] sadump_info: Return empty string instead of NULL
Found via -Werror:

  In file included from makedumpfile.h:47,
                   from makedumpfile.c:16:
  makedumpfile.c: In function 'initial':
  makedumpfile.c:4546:29: error: '%s' directive argument is null [-Werror=format-overflow=]
   4546 |                         MSG("because %s is sadump %s format.\n",
        |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  print_info.h:61:41: note: in definition of macro 'MSG'
     61 |                         fprintf(stdout, x); \
        |                                         ^
  makedumpfile.c:4546:51: note: format string is defined here
   4546 |                         MSG("because %s is sadump %s format.\n",
        |                                                   ^~
  makedumpfile.c:4546:29: error: '%s' directive argument is null [-Werror=format-overflow=]
   4546 |                         MSG("because %s is sadump %s format.\n",
        |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  print_info.h:59:41: note: in definition of macro 'MSG'
     59 |                         fprintf(stderr, x); \
        |                                         ^
  makedumpfile.c:4546:51: note: format string is defined here
   4546 |                         MSG("because %s is sadump %s format.\n",
        |

Signed-off-by: Stefan Wiehler <stefan.wiehler@nokia.com>