[PATCH] arm64: fix two level pmd calculation
While reviewing commit "a9085b70501c arm64: Fix for ARM64 3 level
translation tables" we missed that, it breaks pmd_offset calculation for 2
level translation table. Because of that we get following error messages:

---------------------------------------------------------------------
vtop_arm64: Can't read pmd
---------------------------------------------------------------------

Current patches fixes it.

As a side effect of above fix, it also fixes following compilation warning
introduced in above commit.

---------------------------------------------------------------------
arch/arm64.c: In function 'pmd_offset':
arch/arm64.c:119:3: warning: implicit declaration of function
'get_page_shift_arm64' [-Wimplicit-function-declaration]
   return pmd_offset_pgtbl_lvl_3(pud, vaddr);
   ^
arch/arm64.c: In function 'vtop_arm64':
arch/arm64.c:246:9: warning: unused variable 'puda' [-Wunused-variable]
  pud_t *puda, pudv;
         ^
---------------------------------------------------------------------

Signed-off-by: Pratyush Anand <panand@redhat.com>